# Generated by Django 4.0 on 2022-01-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_creditmodel_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditmodel',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
