# Generated by Django 4.0 on 2022-01-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_creditdebitbuttonmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransfermodel',
            name='tag',
            field=models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], max_length=200),
        ),
    ]
