# Generated by Django 4.0 on 2022-01-10 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_banktransfermodel_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreditDebitButtonModel',
            new_name='CreditDebitTransferButtonModel',
        ),
    ]
