# Generated by Django 4.0 on 2022-01-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_creditdebitbuttonmodel_creditdebittransferbuttonmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransfermodel',
            name='tag',
            field=models.CharField(max_length=200),
        ),
    ]
