# Generated by Django 4.0 on 2022-01-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_banktransfermodel_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditdebittransferbuttonmodel',
            name='btn_type',
            field=models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit'), ('Credit Transfer', 'Credit Transfer'), ('Debit Transfer', 'Debit Transfer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='creditmodel',
            name='tag',
            field=models.CharField(choices=[('Credit', 'Credit')], max_length=200),
        ),
        migrations.AlterField(
            model_name='debitmodel',
            name='tag',
            field=models.CharField(choices=[('Debit', 'Debit')], max_length=200),
        ),
    ]
